- key:               gold-testnet
  name:              Goldcash Testnet
  client:            goldcash                             # API client name.
  server:            http://user:password@127.0.0.1:18332 # Public Goldcash node endpoint.
  height:            22500                                # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://www.goldcash-explorer.co.uk/address/#{address}
    transaction:     https://www.goldcash-explorer.co.uk/tx/#{txid}
  status:            active
